<?php

namespace App\Filament\Admin\Resources\ProformaInvoices;

use App\Filament\Admin\Resources\ProformaInvoices\Pages\ListProformaInvoices;
use App\Models\ProformaInvoice;
use App\Services\ProformaInvoiceService;
use BackedEnum;
use Filament\Actions\Action;
use Filament\Resources\Resource;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

/** LC proforma invoices generated by customers (read-only). */
class ProformaInvoiceResource extends Resource
{
    protected static ?string $model = ProformaInvoice::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedDocumentText;

    protected static string|\UnitEnum|null $navigationGroup = 'Enquiries';

    protected static ?string $navigationLabel = 'Proforma invoices';

    protected static ?int $navigationSort = 5;

    public static function canAccess(): bool
    {
        $user = auth()->user();

        return $user && $user->hasAnyRole(['super_admin', 'admin', 'sales']);
    }

    public static function canCreate(): bool
    {
        return false;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('id', 'desc')
            ->modifyQueryUsing(fn ($query) => $query->with(['user', 'vehicle']))
            ->columns([
                TextColumn::make('invoice_no')->label('Invoice')->searchable()->weight('bold'),
                TextColumn::make('created_at')->label('Created')->dateTime('Y-m-d H:i')->sortable(),
                TextColumn::make('consignee_name')->label('Consignee')->searchable()
                    ->description(fn (ProformaInvoice $r) => $r->consignee_email),
                TextColumn::make('snapshot.title')->label('Vehicle')->limit(35)
                    ->url(fn (ProformaInvoice $r) => $r->vehicle ? route('vehicles.show', $r->vehicle->slug) : null, true),
                TextColumn::make('destination')->label('Destination')
                    ->state(fn (ProformaInvoice $r) => trim(($r->snapshot['port'] ?? '').' / '.($r->snapshot['country'] ?? ''), ' /')),
                TextColumn::make('total_cif')->label('Total CIF')->money('USD')->sortable(),
                TextColumn::make('expires_on')->label('Valid until')->date('Y-m-d')
                    ->color(fn (ProformaInvoice $r) => $r->isExpired() ? 'gray' : 'success'),
            ])
            ->recordActions([
                Action::make('pdf')
                    ->label('PDF')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->action(fn (ProformaInvoice $r) => response()->streamDownload(
                        fn () => print (app(ProformaInvoiceService::class)->pdf($r)),
                        $r->fileName(),
                        ['Content-Type' => 'application/pdf'],
                    )),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListProformaInvoices::route('/'),
        ];
    }
}
