@props(['card'])
<table role="presentation" class="card" width="268" cellpadding="0" cellspacing="0" border="0" style="width:268px;border:1px solid #E4E4E8;background:#FFFFFF;border-collapse:separate;">
<tr><td style="padding:0;"><a href="{{ $card['url'] }}" data-utm="{{ $card['ref'] }}" target="_blank" style="text-decoration:none;"><img class="card-img" src="{{ $card['img'] }}" width="266" height="153" alt="{{ $card['alt'] }}" style="display:block;width:266px;height:153px;border:0;background:#E4E4E8;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;color:#55555C;"></a></td></tr>
<tr><td style="padding:14px 14px 0 14px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>@if ($card['badge'])<td style="background:{{ $card['badgeColor'] }};padding:3px 7px;font-family:Arial, Helvetica, sans-serif;font-size:10px;line-height:14px;font-weight:bold;letter-spacing:1px;color:#FFFFFF;">{{ $card['badge'] }}</td><td width="8" style="width:8px;">&nbsp;</td>@endif<td style="font-family:'Courier New',Courier,monospace;font-size:12px;line-height:14px;font-weight:bold;color:#E30613;">#{{ $card['ref'] }}</td></tr></table></td></tr>
<tr><td class="card-title" style="padding:10px 14px 0 14px;font-family:Arial, Helvetica, sans-serif;font-size:15px;line-height:20px;font-weight:bold;color:#111114;text-transform:uppercase;">{{ $card['title'] }}</td></tr>
<tr><td class="card-meta" style="padding:6px 14px 0 14px;font-family:Arial, Helvetica, sans-serif;font-size:11px;line-height:16px;color:#6B6B73;">{{ $card['meta'] }}</td></tr>
<tr><td style="padding:12px 14px 14px 14px;font-family:Arial, Helvetica, sans-serif;"><div style="font-size:10px;line-height:14px;font-weight:bold;letter-spacing:1px;color:#6B6B73;">FOB</div>@if ($card['oldPrice'])<span class="old-price" style="font-size:13px;line-height:24px;color:#6B6B73;text-decoration:line-through;">{{ $card['oldPrice'] }}</span>&nbsp;&nbsp;@endif<span style="font-size:21px;line-height:24px;font-weight:bold;color:#E30613;">{{ $card['price'] }}</span></td></tr>
<tr><td style="padding:0 14px 14px 14px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td class="btn" bgcolor="#0D0D0F" style="background:#0D0D0F;text-align:center;"><a href="{{ $card['url'] }}" data-utm="{{ $card['ref'] }}" target="_blank" style="display:block;padding:12px 0;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-weight:bold;letter-spacing:1px;color:#FFFFFF;text-decoration:none;">VIEW VEHICLE &rsaquo;</a></td></tr></table></td></tr>
</table>
