@props(['card'])
<table role="presentation" class="card" width="176" cellpadding="0" cellspacing="0" border="0" style="width:176px;border:1px solid #E4E4E8;background:#FFFFFF;border-collapse:separate;">
<tr><td style="padding:0;"><a href="{{ $card['url'] }}" data-utm="{{ $card['ref'] }}" target="_blank" style="text-decoration:none;"><img class="card-img" src="{{ $card['img'] }}" width="174" height="100" alt="{{ $card['alt'] }}" style="display:block;width:174px;height:100px;border:0;background:#E4E4E8;font-family:Arial, Helvetica, sans-serif;font-size:11px;line-height:14px;color:#55555C;"></a></td></tr>
<tr><td class="card-pad" style="padding:9px 10px 0 10px;"><table role="presentation" cellpadding="0" cellspacing="0" border="0"><tr>@if ($card['badge'])<td class="card-badge" style="background:{{ $card['badgeColor'] }};padding:2px 5px;font-family:Arial, Helvetica, sans-serif;font-size:9px;line-height:12px;font-weight:bold;letter-spacing:1px;color:#FFFFFF;">{{ $card['badge'] }}</td><td width="6" style="width:6px;">&nbsp;</td>@endif<td class="card-ref" style="font-family:'Courier New',Courier,monospace;font-size:11px;line-height:12px;font-weight:bold;color:#E30613;">#{{ $card['ref'] }}</td></tr></table></td></tr>
<tr><td class="card-title card-pad" style="padding:7px 10px 0 10px;font-family:Arial, Helvetica, sans-serif;font-size:12px;line-height:16px;font-weight:bold;color:#111114;text-transform:uppercase;">{{ $card['title'] }}</td></tr>
<tr><td class="card-meta card-pad" style="padding:4px 10px 0 10px;font-family:Arial, Helvetica, sans-serif;font-size:10px;line-height:14px;color:#6B6B73;">{{ $card['meta'] }}</td></tr>
<tr><td class="card-pad" style="padding:8px 10px 10px 10px;font-family:Arial, Helvetica, sans-serif;"><div style="font-size:9px;line-height:12px;font-weight:bold;letter-spacing:1px;color:#6B6B73;">FOB</div>@if ($card['oldPrice'])<span class="old-price" style="font-size:11px;line-height:20px;color:#6B6B73;text-decoration:line-through;">{{ $card['oldPrice'] }}</span>&nbsp;@endif<span class="card-price" style="font-size:16px;line-height:20px;font-weight:bold;color:#E30613;">{{ $card['price'] }}</span></td></tr>
<tr><td class="card-pad" style="padding:0 10px 10px 10px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0"><tr><td class="btn" bgcolor="#0D0D0F" style="background:#0D0D0F;text-align:center;"><a href="{{ $card['url'] }}" data-utm="{{ $card['ref'] }}" target="_blank" style="display:block;padding:9px 0;font-family:Arial, Helvetica, sans-serif;font-size:11px;line-height:14px;font-weight:bold;letter-spacing:1px;color:#FFFFFF;text-decoration:none;">VIEW VEHICLE &rsaquo;</a></td></tr></table></td></tr>
</table>
